### ISSUE TITLE
Failing to create Code build job when using Cloudformation template 

### ISSUE THREAD

**Issue by rkowtha** [awslabs/service-workbench-on-aws#428]
Referenced in Implementation Guide for Service work bench (https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/automated-deployment.html ) used the following link https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?templateURL=https:%2F%2Fs3.amazonaws.com%2Fsolutions-reference%2Fservice-workbench-on-aws%2Flatest%2Fservice-workbench-on-aws.template  to build the Server Work Bench using Cloud formation template. 
Failing in Code build. Below are the log details. Any fix to this is helpful. Thanks

[Container] 2021/04/07 15:28:58 Running command npm install -g pnpm
--
980 | /usr/local/bin/pnpm -> /usr/local/lib/node_modules/pnpm/bin/pnpm.cjs
981 | /usr/local/bin/pnpx -> /usr/local/lib/node_modules/pnpm/bin/pnpx.cjs
982 | npm WARN notsup Unsupported engine for pnpm@6.0.1: wanted: {"node":">=12.17"} (current: {"node":"12.16.1","npm":"6.13.4"})
983 | npm WARN notsup Not compatible with your version of node/npm: pnpm@6.0.1
984 |  
985 | + pnpm@6.0.1
986 | added 1 package in 0.997s
987 |  
988 | [Container] 2021/04/07 15:29:04 Running command echo "Installing dependencies"
989 | Installing dependencies
990 |  
991 | [Container] 2021/04/07 15:29:04 Running command ./scripts/install.sh
992 | About to install all dependencies, please hang in there tight
993 | /usr/local/bin/pnpm
994 | /codebuild/output/src838261437/src/main/solution /codebuild/output/src838261437/src
995 | ERROR: This version of pnpm requires at least Node.js v12.17
996 | The current version of Node.js is v12.16.1
997 | Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
998 |  
999 | [Container] 2021/04/07 15:29:04 Command did not exit successfully ./scripts/install.sh exit status 1
1000 | [Container] 2021/04/07 15:29:04 Phase complete: INSTALL State: FAILED
1001 | [Container] 2021/04/07 15:29:04 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./scripts/install.sh. Reason: exit status 1

**Comment by ashaman25** [comment]
995 | ERROR: This version of pnpm requires at least Node.js v12.17
996 | The current version of Node.js is v12.16.1

Try updating your version of NodeJS.

I used WSL and the repo's had older versions of Node. I ran these commands and upgraded to version 14.16.

2017  30/03/21  15:45:12 yum remove nodejs
 2018  30/03/21  15:48:22 yum clean
 2019  30/03/21  15:48:28 yum clean all
 2020  30/03/21  15:48:48 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
 2021  30/03/21  15:49:36 export NVM_DIR="$HOME/.nvm"
 2022  30/03/21  15:49:36 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 2023  30/03/21  15:49:38 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 2024  30/03/21  15:49:52 nvm ls
 2025  30/03/21  15:50:38 nvm install v14.16.0
 2026  30/03/21  15:58:53 node --version
 2027  30/03/21  15:59:14 npm install -g pnpm
 2028  30/03/21  16:01:19 sudo yum install go

**Comment by rkowtha** [comment]
The cloudformation template is building the code using AWS CodeBuild and I cannot update the nodejs of the container

**Comment by rsmayda** [comment]
Thanks for reaching out. This is an unfortunate break due to PNPM update and AWS CodeBuild discrepancy. We have fixed this in our GitHub repository: https://github.com/awslabs/service-workbench-on-aws/commit/262b5c8f937d49a47be29a97ab39ff1efcfe02fd. We are working towards updating the AWS Solution code as well.

For the time being we advise you to work off of the latest tag: https://github.com/awslabs/service-workbench-on-aws/tree/v2.1.4

**Comment by rkowtha** [comment]
Looking forward for the updated AWS Solution code. thanks.

**Comment by SanketD92** [comment]
@rkowtha Just wanted to update you that the AWS Solution code has now been fixed.

**Comment by rmontroy** [comment]
@rsmayda @SanketD92 
This is still failing when [upgrading the solution implementation](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/installation_guide/upgrading/solutions.md).




```
957 | [Container] 2021/10/01 15:06:58 Running command aws s3 cp s3://$GLOBAL_BUCKET_NAME-$REGION_NAME/$OBJECT_KEY_NAME/generate-config.sh ./scripts/generate-config.sh
958 | Completed 468 Bytes/468 Bytes (3.8 KiB/s) with 1 file(s) remaining
959 | download: s3://solutions-us-east-1/service-workbench-on-aws/v1.4.7/generate-config.sh to scripts/generate-config.sh
960 |  
961 | [Container] 2021/10/01 15:06:59 Running command chmod +x ./scripts/generate-config.sh
962 |  
963 | [Container] 2021/10/01 15:06:59 Running command ./scripts/generate-config.sh
...
979 | [Container] 2021/10/01 15:06:59 Running command npm install -g pnpm
980 | /usr/local/bin/pnpm -> /usr/local/lib/node_modules/pnpm/bin/pnpm.cjs
981 | /usr/local/bin/pnpx -> /usr/local/lib/node_modules/pnpm/bin/pnpx.cjs
982 | npm WARN notsup Unsupported engine for pnpm@6.16.0: wanted: {"node":">=12.17"} (current: {"node":"12.16.1","npm":"6.13.4"})
983 | npm WARN notsup Not compatible with your version of node/npm: pnpm@6.16.0
984
```

**Comment by nguyen102** [comment]
Hi @rmontroy do you have a current SWB instance that was deployed using [SWB Solutions](https://aws.amazon.com/solutions/implementations/service-workbench-on-aws/?did=sl_card&trk=sl_card). What version number is it? 
And then to confirm you're trying to update that SWB instance to version `1.4.7`?

**Comment by rmontroy** [comment]
Testing the upgrade process from 1.4.5. I added the output to my comment above so you could see the new version.

**Comment by nguyen102** [comment]
I tested a fresh install with version `1.4.7` and it didn't have this issue. I see that this command is being run ` Running command npm install -g pnpm` in your log file.

That is from CodeBuild in version `1.4.5`. It's using the old build script to upgrade to version `1.4.7`. 

I would recommend doing a fresh install with version `1.4.7` which [locks down](https://github.com/awslabs/service-workbench-on-aws/blob/aws-solution/deployment/service-workbench-on-aws.template#L415) the `pnpm` version. 

Note: The SWB solutions was published in May 2021, which is 5 months old now. To get the latest code I would recommend following the guide [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Installation_Guide.pdf). We've made many bug fixes and feature enhance since May.

**Comment by rmontroy** [comment]
Noted. Can I install from a feature branch? I'm anxious to try out RStudio behind AppStream.

**Comment by nguyen102** [comment]
Our feature branch for AppStream is [here](https://github.com/awslabs/service-workbench-on-aws/tree/feat-secure-workspace-egress). However for P1 we will only support Linux, WIndows, and Sagemaker instances behind AppStream. Support for RStudio with AppStream is coming later.

Finally, do not use the feature branch code for production. We are going through Penetration testing for the feature branch and there will likely be additional changes before the code is ready for production.
