### ISSUE TITLE
[Bug] Notebook file has been changed on disk

### ISSUE THREAD

**Issue by simranmakwana** [awslabs/service-workbench-on-aws#691]
**Describe the bug**
When saving edits to Jupyter Notebooks in SWB, the following popup appears with high frequency: "Notebook changed The notebook file has changed on disk since the last time we opened or saved it. Do you want to overwrite the file on disk with the version open here, or load the version on disk (reload the page)?
To properly save edits, users must manually select "Overwrite". 

**To Reproduce**
1. Make any edit in a Jupyter Notebook
2. Save the edits (using command+s or through File>save dialog)
note: While the previous steps will reproduce the behavior, the behavior will also happen at other apparently random times (perhaps due to autosave).

**Expected behavior**
Changes that a user makes to a Jupyter Notebook will save.

**Screenshots**
<img width="717" alt="Screen Shot 2021-08-27 at 9 47 48 AM" src="https://user-images.githubusercontent.com/56128463/131750144-8214ae39-8978-4d63-a464-1ab5c451733d.png">

**Versions (please complete the following information):**
 - Release Version installed: 3.3.1

**Additional context**

**Comment by jn1119** [comment]
Hey @simranmakwana, This seems like a Jupyter specific bug and I do see an [issue for it in Jupyter Github repo](https://github.com/jupyter/notebook/issues/484) Some folks on the thread have complained about the issue occurring specifically in Chrome browser. Are you using Chrome? And is it possible for you to try out a different browser like Safari or Firefox?

And just to be sure, can you confirm if the file is not being modified concurrently by other users or some other workflow?

**Comment by simranmakwana** [comment]
Hi @jn1119 , thanks for your response!

We did as you suggested and tested in the 3 different browsers. The same issue occurred every time.
We are sure that the file is not being modified by any other users, but we are not sure about what you mean by the 'workflow' part.

One thing we did notice is that it only appears to happen with files stored in S3.
Based on the issue you linked: https://github.com/jupyter/notebook/issues/484
We think that maybe it could be due to one of the following issues:

- the Jupyter notebook and the s3 bucket are doing some kind of autosave, and the timestamps from each do not line up

- the time of the s3 bucket is not synced with the time in SWB

Is there any way to check this? Do you know a way to solve it?

@avillach

**Comment by carvantes** [comment]
The root cause is that Goofys presents an inaccurate last-modified date  right after updating a file.

When a file is modified, the content is updated immediately, but the last-modified date is not. There is a BIG delay ( ~ 1 minute) before Goofys updates the last-modified date.

#### Small experiment to observe the delay

Here's a small script that updates a file and then prints the last-updated time for the filesystem and for S3

Interestingly, The file is uploaded almost immediately to S3 (you can see the S3 timestamp updated), but it still takes a while for the last-updated date on the file system to get updated

```
sh-4.2$ goofys -v
goofys version 0.21.0-42c567cafc27c7f68086f9709a19f03b56e2e80e
```

```
sh-4.2$ echo '=============' && date && ls -la --time-style=full-iso | grep x.txt && aws s3 ls s3://824558622956-e2etest-va-swb-studydata/users/service-workbench-dev+admin@amazon.com/nestorba-study/swb-test/ | grep x.txt

=============
Wed Sep  8 19:29:20 UTC 2021
-rw-r--r-- 1 ec2-user ec2-user       9 2021-09-08 19:25:48.000000000 +0000 x.txt
2021-09-08 19:25:48          9 x.txt

sh-4.2$ echo "some new text" > x.txt
sh-4.2$ for run in {1..100}; do echo '=============' && date && ls -la --time-style=full-iso | grep x.txt && aws s3 ls s3://824558622956-e2etest-va-swb-studydata/users/service-workbench-dev+admin@amazon.com/nestorba-study/swb-test/ | grep x.txt;done

=============
Wed Sep  8 19:29:23 UTC 2021
-rw-r--r-- 1 ec2-user ec2-user      14 2021-09-08 19:25:48.000000000 +0000 x.txt
2021-09-08 19:29:24         14 x.txt
=============
Wed Sep  8 19:29:26 UTC 2021
-rw-r--r-- 1 ec2-user ec2-user      14 2021-09-08 19:25:48.000000000 +0000 x.txt
2021-09-08 19:29:24         14 x.txt

...

=============
Wed Sep  8 19:30:23 UTC 2021
-rw-r--r-- 1 ec2-user ec2-user      14 2021-09-08 19:29:24.000000000 +0000 x.txt
2021-09-08 19:29:24         14 x.txt
```

#### Detailed sequence of the bug on the Jupyter UI

Jupyter decides whether saving a file would overwrite something else based entirely on the last-modified date. It never hashes the file contents nor anything like that.

Notebook `*.ipynb` file starts with a last modified at `04:00:00`

- `05:00:00` - Jupyter UI loads the notebook. And stores a `last_modified`  time of `04:00:00`
- `05:01:00` - User saves notebook changes (or auto save happens). Jupyter UI posts the updated notebook file and gets back a last-modified date of `04:00:00` and stores it as `last_modified`. This because Goofys does not immediately update the last-modified date
- `05:02:00` - Behind the scenes, Goofys  finally updates the last-modified date to `05:01:00`
- `05:03:00` - User attempts to save notebook changes (or auto save happens). Jupyter UI makes a request to get a last-modified date and receives `05:01:00`. `05:01:00` is greater than the  `last_modified` of `04:00:00` , so the “overwrite warning popup” is shown.

The issue continues to happen over and over since whenever Jupyter saves the notebook, it always gets back a "bad" last-modified date from Goofys.

When the warning popup appears, you can see in the browser console a msg like:
```
Last saving was done on `Tue Sep 07 2021 19:22:59 GMT-0500 (Central Daylight Time)`(save-success:2021-09-08T00:22:59Z), while the current file seem to have been saved on `2021-09-08T17:11:34Z`
```

**Comment by carvantes** [comment]
Updating to goofys 0.24.0 should fix the issue

I ran the same experiment on goofys 0.24.0 and the results are very different (btw It's amazing how FAST the uploads to S3 are. I tested with a 256MB file and it took less than a second). In the latest version the last-updated time is updated at the time the file content is updated. 

The “overwrite warning popup” never showed up when using goofys 0.24.0

**Comment by carvantes** [comment]
After deploying the fix, existing SageMaker workspaces need to be restarted to pick up the change. Newly created SageMaker workspaces willnaturally pick up the change as well.

**Comment by simranmakwana** [comment]
Hi everyone, 

First, thank you so much for your prompt response in helping us fix this issue.
I'd like to reopen this issue because although we have seen a **decrease in the frequency of this popup message**, we are **still seeing it in new and restarted SageMaker workspaces**.

Please let me know if there is any other information I can provide which may help.
